/**Hide the close icon of quick-actions-panel*/
.slds-modal__header .slds-modal__close{
	display: none;
}
/**Modify the width and bottom padding of standard quick-actions-panel*/
.slds-modal__container{
    width: 90% !important;
    max-width: 90% !important;
	padding-bottom: 3rem !important;
}
/**Hide the standard scrollbar*/
::-webkit-scrollbar {
    width: 0;  /* Remove scrollbar space */
    background: transparent;  /* Optional: just make scrollbar invisible */
}